services:
  - type: web
    name: finance-backend
    env: python
    plan: free
    buildCommand: pip install fastapi uvicorn
    startCommand: python backend/simple_main.py
    envVars:
      - key: PORT
        value: 10000 